# PKM v2.1 News Educator - Sources Configuration
# 入门成长版：只抓"资讯口"，不抓版本口

settings:
  window_hours: 24
  max_items_per_source: 30
  top_items_in_pack: 10
  timezone: "Asia/Kuala_Lumpur"

filters:
  whitelist_domains: ["github.com", "www.youtube.com", "youtube.com", "huggingface.co"]
  drop_release_as_event: true  # 自动过滤 release 作为主体事件
  min_signal_score: 6.0         # 最低信号评分

# 基础概念 -> MOC 挂载路径（按你现有结构）
learning_map:
  cache: "10-领域知识/01-计算机/数据库/Redis-MOC"
  thread: "10-领域知识/01-计算机/Java/02-并发/并发-MOC"
  jvm: "10-领域知识/01-计算机/Java/03-JVM/JVM-MOC"
  db_index: "10-领域知识/01-计算机/数据库/MySQL-MOC"
  transaction: "10-领域知识/01-计算机/数据库/事务-MOC"
  devops: "10-领域知识/01-计算机/工程化与DevOps/DevOps-MOC"
  ai_dev: "10-领域知识/06-学习方法与效率/AI开发-MOC"

sources:
  github:
    # 以"讨论/事故/风险/性能争议"为资讯口
    # GitHub Search Issues API: https://docs.github.com/en/rest/search
    queries:
      - "repo:spring-projects/spring-boot (label:bug OR label:regression OR label:performance) sort:updated-desc"
      - "repo:redis/redis (label:bug OR label:performance OR label:security) sort:updated-desc"
      - "repo:baomidou/mybatis-plus (label:bug OR label:performance) sort:updated-desc"
      - "repo:alibaba/arthas (label:bug OR label:question) sort:updated-desc"
      - "language:java (label:security OR label:vulnerability) sort:updated-desc"

  youtube:
    # YouTube Channel RSS: https://www.youtube.com/feeds/videos.xml?channel_id=...
    # 请替换为你关注的频道 ID
    channel_ids:
      # - "UCkw4JCwteGrDHIsyIIKo4tQ"  # 示例：黑马程序员
      # - "UC_x5XG1OV2P6uZZ5FSM9Ttw"  # 示例：Google Developers

  huggingface:
    # Hugging Face Trending API: https://huggingface.co/api/trending
    trending: true
    keywords: ["agent", "rag", "tool", "code", "java"]

# 信号评分权重（用于排序优先级）
scoring:
  github_comments_weight: 0.08   # 评论数权重
  github_reactions_weight: 0.06  # 反应数权重
  label_boost:
    security: 2.5
    regression: 2.5
    bug: 2.0
    performance: 2.0
    incident: 2.5
  keyword_boost:
    - incident
    - outage
    - vulnerability
    - cve
    - regression
    - breaking
    - 性能
    - 宕机
    - 漏洞
    - 复盘
    - 最佳实践
    - 坑
