filters:
  # 关键：彻底压制"版本更新流水账"
  drop_release_as_event: true
  drop_changelog: true
  drop_version_bump_only: true

  # 新手友好：没有可摘录内容就不要
  require_excerpt: true

  # 信号阈值（越高越严格）
  min_signal_score: 7.0

whitelist_domains:
  - github.com
  - youtube.com
  - huggingface.co

github:
  collect:
    security_advisories: true
    issues: true
    discussions: true
    releases: false
  query_hints:
    # 让系统更像"资讯"而不是"更新"
    - "outage"
    - "incident"
    - "regression"
    - "memory leak"
    - "deadlock"
    - "performance"
    - "security"
    - "best practice debate"

youtube:
  mode: "channel_whitelist"
  require_transcript_or_description: true

huggingface:
  collect:
    tutorials: true
    papers: true
    trending_models: false   # 避免"上新榜"噪音
  query_hints:
    - "fine-tuning tutorial"
    - "evaluation"
    - "benchmark"
    - "deployment"

learning_map:
  cache: "10-领域知识/01-计算机/数据库"
  db_index: "10-领域知识/01-计算机/数据库"
  transaction: "10-领域知识/01-计算机/数据库"
  thread: "10-领域知识/01-计算机/Java/02-并发"
  jvm: "10-领域知识/01-计算机/Java/03-JVM"
  spring: "10-领域知识/01-计算机/Java/04-Spring"
  devops: "10-领域知识/01-计算机/工程化与DevOps"
  ai_dev: "10-领域知识/06-学习方法与效率"

output_paths:
  candidate_pack_dir: "00-收集箱/News-Inbox/"
  daily_dir: "02-学习记录/01-日报/"
  drafts_dir: "00-收集箱/News-Knowledge-Drafts/"
  moc_file: "01-导航索引/News-MOC.md"
